<?php

namespace App\Tests;

use PHPUnit\Framework\TestCase;

class ContactUnitTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testGetContactCollection(): void
    {
        $this->assertTrue(true);
    }
}
